### ISSUE TITLE
detect other samll objects

### ISSUE THREAD

**Issue by zhaobingbingbing** [alexattia/ExtendedTinyFaces#3]
If I want to detect other small objects
not only face
how should I do?
THANK YOU

**Comment by SharoneDayan** [comment]
We use a Tiny Face Detector as introduced by P. Hu in Finding Tiny Faces [1]. 
Thus, our analysis focuses on faces.
If you want to extend this work to other tiny objects, you will have to not only detect them but also segment them. You should take a look at Mask R-CNN [2] and ClusterNet [3].

### References 
[[1]](https://arxiv.org/abs/1612.04402) Peiyun Hu and Deva Ramanan. Finding Tiny Faces. 2017.  
[[2]](https://arxiv.org/pdf/1703.06870.pdf) Kaiming He, Georgia Gkioxari, Piotr Dollar and Ross Girshick. Mask R-CNN. 2017
[[3]](https://arxiv.org/pdf/1704.02694.pdf) Rodney LaLonde, Dong Zhang and Mubarak Shah. ClusterNet: Detecting Small Objects in Large Scenes by Exploiting Spatio-Temporal Information. 2017

**Comment by SharoneDayan** [comment]
Fixes #3

**Comment by alexattia** [comment]
It would be possible to detect other small objects but you have to re-train the entire model (not provided in this repo) for one other object (instead of faces).   
For this, you have to train multiple detectors with shared weights for different image sizes (the image ratios must be customized depending on your objects). 

This approach would be only for one object detector. If you want to detect multiple small objects in an image, I think that  @SharoneDayan is right and you should take a look at Mask R-CNN [2] and ClusterNet [3].
